apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
    author: Gedda
spec:
  containers:
    - name: myngnix
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
