apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: Aditya
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30008
  selector:
    type: ci-cd
    author: Gedda