apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels: 
    author: Gedda
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30008
  selector:
    type: appserver